name: panorama
description: Panorama -- A 360-degree panorama viewer.
version: 0.4.3
homepage: https://github.com/zesage/panorama

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cube:
    git:
      url: https://github.com/WafikSleim/flutter_cube.git
  motion_sensors: 
    git: https://github.com/zesage/motion_sensors.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
